### ISSUE TITLE
make install でインストールができない

### ISSUE THREAD

**Issue by IkuyaYamada** [dondakeshimo/todo-cli#18]
github から pull したのちに

`make install`

をしても todo コマンドが利用できない。

`make build`

すると todo という名の実行ファイルを利用することはできる

**Comment by dondakeshimo** [comment]
@IkuyaYamada 

このリポジトリはどの様に取得しただろうか？

`go get ~~~` ならgo moduleみたいな機能がonになると思うのだが、
`git clone ~~~` したらその限りではなく、`go install` が効かないかもしれない。
てかそもそも `go install` でインストールして貰えば良い気もする。(できるか知らない)

**Comment by IkuyaYamada** [comment]
git clone してから、go install をしやした

**Comment by dondakeshimo** [comment]
承知致した
とりあえず混乱招きそうだからmake installは消してしまおうかな〜
git cloneしたらgo modules がonになっていなくてgo installがうまくいかないのだろうな
面倒だ

**Comment by dondakeshimo** [comment]
> git clone してから、go install をしやした

make install とのこと

**Comment by dondakeshimo** [comment]
@IkuyaYamada 

```
$ go get github.com/dondakeshimo/todo-cli/cmd/todo
```

をやってみてくれない？

**Comment by IkuyaYamada** [comment]
`$go get github.com/dondakeshimo/todo-cli/cmd/todo`

でもインストールされませんね。

`
14:46:46 ~
	$ go get github.com/dondakeshimo/todo-cli/cmd/todo 
14:48:34 ~
	$ todo                                            
zsh: correct 'todo' to 'od' [nyae]? n
zsh: command not found: todo
`

**Comment by dondakeshimo** [comment]
```
$ ls $(go env GOPATH)/bin
```

にtodoがない？

**Comment by IkuyaYamada** [comment]
`
14:50:36 ~
	$ ls $(go env GOPATH)/bin
dlv*          go-outline*   gocode*       godef*        golint*       gopkgs*       gopls*        goreturns*    guru*         todo*
fillstruct*   go-symbols*   gocode-gomod* godoctor*     gomodifytags* goplay*       gorename*     gotests*      impl*
`

"todo" exists

**Comment by dondakeshimo** [comment]
おるな
てことはあれだ

.zshrcに
```
export PATH=$PATH:$(go env GOPATH)/bin
```

とかしてあげれば問題なさそう

**Comment by IkuyaYamada** [comment]
resolved 👍 
となると make install でインストールできなかった説も怪しい

**Comment by dondakeshimo** [comment]
確かに笑
普通にできる説はあるのだろうか

普通にbinaryをremoveしてもう一度make install してみればわかるかな

**Comment by IkuyaYamada** [comment]
`$ rm -f $(go env GOPATH)/bin/todo  `

からの、
`$ git clone git@github.com:dondakeshimo/todo-cli.git`
`$make install`                                                                                                                             
でいけましたやで！                                                                                                                        

there existed a bug in my head 😇

**Comment by dondakeshimo** [comment]
That's nice to me!
Ok, close this issue.
Thank you!
