### ISSUE TITLE
WIki をまとめる

### ISSUE THREAD

**Issue by IkuyaYamada** [dondakeshimo/todo-cli#29]
齟齬が生じないように WIki にまとめておく
- Issue/PR/Projects の運用方法

**Comment by IkuyaYamada** [comment]
Wiki もbranch 切って開発？

**Comment by dondakeshimo** [comment]
wiki使ったことないのだよな。
wikiってコード管理と別だと思っていたけどbranchの概念とかあるのかい？

**Comment by dondakeshimo** [comment]
markdownをリポジトリに加えるということならブランチは切る

**Comment by IkuyaYamada** [comment]
そういう感じではなさそう

バージョン管理とかはできるけども、あくまでリポジトリの外側ぽい
https://docs.github.com/ja/free-pro-team@latest/github/building-a-strong-community/adding-or-editing-wiki-pages

**Comment by dondakeshimo** [comment]
なるほどにあ
そしたら普通に書いていってくれれば！

**Comment by IkuyaYamada** [comment]
got it
いったんこれまでのところを Wiki にまとめてこのissue は閉じるでござんす

**Comment by IkuyaYamada** [comment]
Wiki の事始めはとりあえず終了。多分リポジトリの情報とか書いておくところだと思うので、こういう使い方じゃなさそうな気もしているが、とりあえず done

**Comment by dondakeshimo** [comment]
運用方法とかちょうどそこで良いのではないだろうか？多分
ありがと
