### ISSUE TITLE
slack notifyの実装

### ISSUE THREAD

**Issue by dondakeshimo** [dondakeshimo/todo-cli#5]
slackにその時間に通知を送るとかで良いかなと思う。
(slackなのでゆくゆくはslack上でdoneボタンを押せるようになるとかが良いのだろうが今は無理)

**Comment by dondakeshimo** [comment]
<details>
<summary> lineでの会話 </summary>

```
01:39 山田郁也 Ikuya 認証情報を環境変数かなんかに入れといて、
01:40 山田郁也 Ikuya それかconfigファイルに書いといて
01:40 山田郁也 Ikuya えーぴーあいたたくんかな
01:40 山田郁也 Ikuya aws cli の知識が活かされそうだぞぉ
01:40 山田郁也 Ikuya 知らんけど
01:40 山田郁也 Ikuya スタンプ
01:42 下村 拓 configの想定だな
todoの項目jsonファイルに突っ込んでいるだけなので、そこに追加すれば良いかなと考えている
01:42 下村 拓 ただ、read onlyのファイルだから、todo-cli経由で登録させる感じにしたい
01:43 山田郁也 Ikuya aws config
01:43 山田郁也 Ikuya で設定するアレな感じかな？
01:43 山田郁也 Ikuya なんとなくイメージできたわ
01:43 下村 拓 おそらくそうなるのではなかろうか？？
01:44 下村 拓 aws config全く覚えてないが笑
01:44 下村 拓 あ、メールアドレス
01:44 山田郁也 Ikuya いくつかプロファイル分ければいろんなチャネルに送れそうだな
01:45 山田郁也 Ikuya まあ一旦は最小機能で実装しよう笑
```

</details>

**Comment by IkuyaYamada** [comment]
着手
in feature/SlackNotification

**Comment by dondakeshimo** [comment]
@IkuyaYamada 

着手し始めたら、
https://github.com/dondakeshimo/todo-cli/projects/1

をin progressに移動させておく運用で！
これカッコ良いから好きなんやけど、yahooのチームで俺しか使っていない笑

**Comment by IkuyaYamada** [comment]
Status changed 
Work in progress (ただし進捗があるとは限らない)

**Comment by dondakeshimo** [comment]
issueはenhancementとかbugのラベルのままでおけ！
PRに対してwork in progressとready in reviewだな

**Comment by dondakeshimo** [comment]
https://github.com/dondakeshimo/todo-cli/projects/1

ここのチケットを横にスライドさせるだけお願い

**Comment by dondakeshimo** [comment]
着手のタイミングで
https://github.com/dondakeshimo/todo-cli/projects/1
のチケットをin progressの列に移動させる

PRのlabelは単なるレビューするかしないかの判断用だな

**Comment by dondakeshimo** [comment]
https://github.com/dondakeshimo/todo-cli/issues/5#event-4075310006
good
